# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Docker Build

on:
  workflow_call:
    inputs:
      branch-name:
        description: Name of the branch to checkout
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Build Docker image
        run: make docker-build
