# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Canonical Ltd.
name: Integration tests for PFCP Agent & UP4

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Integration tests BESS
        run: |
          DOCKER_TARGETS=pfcpiface DOCKER_TAG=integration make docker-build
          MODE=docker DATAPATH=up4 go test -v -count=1 -failfast -timeout 15m ./test/integration/...
